[package]
name = "saturn-v-client"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
saturn-v-protocol.workspace = true
reqwest-eventsource = "0.6"
cfg-if = "1.0.3"
thiserror.workspace = true

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["json", "rustls-tls"]

[features]
# Enables access to invalid network requests for testing server implementations.
invalid-requests = []
