base_url = "https://marceline-cramer.github.io/saturn-v"
compile_sass = true
build_search_index = true
title = "Saturn V"
theme = "tabi"

[markdown]
bottom_footnotes = true

[markdown.highlighting]
theme = "catppuccin-frappe"
style = "class"
extra_grammars = ["../vscode-ext/syntaxes/kerolox.tmGrammar.json"]

[extra]
# override_serif_with_sans = true
favicon_emoji = "ü™ê"
show_previous_next_article_links = true
copy_button = true
feed_icon = true
show_author = true
stylesheets = ["css/custom.css"]
invert_previous_next_article_links = true
mermaid = true
footnote_backlinks = true

allowed_domains = [
    { directive = "font-src", domains = [
        "'self'",
        "data:",
    ] },
    { directive = "img-src", domains = [
        "'self'",
        "https://*",
        "data:",
    ] },
    { directive = "script-src", domains = [
        "'self' 'wasm-unsafe-eval'",
    ] },
    { directive = "style-src", domains = [
        "'self'",
    ] },
    { directive = "frame-src", domains = [
        "player.vimeo.com",
        "https://www.youtube-nocookie.com",
    ] },
]

[[extra.menu]]
name = "Docs"
url = "docs"
trailing_slash = true

[[extra.menu]]
name = "Blog"
url = "blog"
trailing_slash = true

[[extra.menu]]
name = "Discord"
url = "https://discord.gg/apTv6WEhpn"
trailing_slash = false

[[extra.menu]]
name = "GitHub"
url = "https://github.com/marceline-cramer/saturn-v"
trailing_slash = false

[extra.giscus]
enabled_for_all_posts = false
automatic_loading = true
lazy_loading = true
repo = "marceline-cramer/saturn-v"
repo_id = "R_kgDOOZoxkw"
category = "Blog"
category_id = "DIC_kwDOOZoxk84CrhD3"
mapping = "og:title"
strict_title_matching = 0
enable_reactions = 1
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""                            # Leave blank to match the page's language.
