[package]
name = "saturn-v-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
ordered-float.workspace = true
saturn-v-ir.workspace = true
serde.workspace = true
thiserror.workspace = true
