[package]
name = "saturn-v-eval"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
batsat = "0.6.0"
bitvec = { version = "1", features = ["serde"] }
differential-dataflow.workspace = true
flume.workspace = true
futures-util.workspace = true
indexmap.workspace = true
rustsat = "0.7.1"
# rustsat-cadical = { version = "0.7.1", features = ["v2-1-3"] }
rustsat-batsat = "0.7.1"
saturn-v-ir.workspace = true
serde.workspace = true
timely.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tracing.workspace = true
