on:
  push:
    branches: [ 'main', 'site-*' ]

name: Build and deploy GitHub Pages
jobs:
  site-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: site
          BUILD_ONLY: ${{ github.ref != 'refs/heads/main' }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
