on:
  push:
    branches: [ 'main', 'site-*' ]

name: Build and deploy GitHub Pages
jobs:
  site-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: just,wasm-bindgen

      - name: Prepare site
        run: just prepare-site

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: site
          BUILD_ONLY: ${{ github.ref != 'refs/heads/main' }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
